### ISSUE TITLE
add methods for other collections

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/dlx-js#11]
I don't know why I forgot this before, but we have a bunch of other resource types we need methods for too. Here's the complete list:

https://github.com/digitallinguistics/dlx-api#database-structure

You've finished bundles, items, lexicons, lexicon entries, texts, and phrases.

We still need methods for languages, locations, media, persons, and projects.

Like I said [here](https://github.com/digitallinguistics/dlx-api/issues/3), the client won't be able to perform operations on the users collection, so we won't need any methods for that other than the permissions ones we've been talking about.

The project methods will need to be like bundles. Both bundles and projects are basically just a list of resources that happen to be related to each other. Projects can contain bundles, languages, lexicons, locations, media, and texts. So we'll need methods for each of these like `addBundleToProject` and `removeBundleFromProject`. Just add and remove for each should be fine (let's use remove rather than delete for these, just to be clear that the files aren't actually being deleted, just disassociated).

**Comment by jmangel** [comment]
@dwhieb I'm editing it right now and I placed all the methods for adding or removing anything to a project under /*project methods*/, but before I placed, for example, upsertEntryToLexicon under /*entry methods*/ instead of /*lexicon methods*/. To keep this consistent, do you want me to put the new stuff like addBundleToProject under /*bundle methods*/ instead of under /*project methods*/, or do you want me to move the old stuff like upsertEntryToLexicon from /*entry methods*/ to /*lexicon methods*/? Hope that made sense

**Comment by dwhieb** [comment]
Oh good point. I'd put `upsertEntryToLexicon` under the lexicon methods, and `addBundleToProject` under the project methods. This is because in the API, you have to send a request to `../lexicons/{lexiconId}` to add an entry to it, so it's an operation you're performing on the lexicons table rather than the entries table. (There is no entries table, in fact. Entries are data contained within lexicons.) Same with projects - you'll send a request to the projects collection when you want to add a bundle to it.

So I don't think we'll even have sections for entries or phrases. Those methods will just live under lexicons and texts respectively.

**Comment by jmangel** [comment]
What methods do you need for languages, locations, media, and persons other than adding them to projects?

**Comment by dwhieb** [comment]
Just add and remove is good. Reposting from above:

> So we'll need methods for each of these like `addBundleToProject` and `removeBundleFromProject`. Just add and remove for each should be fine (let's use remove rather than delete for these, just to be clear that the files aren't actually being deleted, just disassociated).

**Comment by jmangel** [comment]
So there will only be the ones in the section /*project methods*/, nothing else for languages, locations, media, etc. specifically? Or addLanguage, addLocation, addMedia etc. as well?

**Comment by dwhieb** [comment]
If I'm understanding your question right, yes, the project methods will only contain methods like `addXToProject` and `removeXFromProject`. We won't have anything under languages, locations, etc. about projects (for now).
