### ISSUE TITLE
get to know the repo

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/dlx-js#3]
# Branches
There are two branches in the repo: `master` and `dev`. Any new changes should happen in dev. When the changes are done, we make a pull request into master, and the other person should review and approve the request before it's merged. Gives us a chance to double check each other's code.

# Files
* test - folder containing any files you only need for testing purposes
* test/index.html - HTML page that includes the SDK script, for testing purposes
* .gitignore - tells GitHub to ignore any of the files included in it; add any filenames you'd like (for example, I have a configuration file in my version of the repo, but it's specific to my machine so I don't want it uploaded to GitHub, because it might interfere with your setup on your machine)
* LICENSE - MIT license
* README.md - Readme, in Markdown format. You should document any important details here as you go. Here's a rundown of Markdown format if you need it: http://daringfireball.net/projects/markdown/syntax. Also here: https://guides.github.com/features/mastering-markdown/
* package.json - This is a configuration file with details about the project. You should add a contributor object for yourself in the `contributors` field (see issue #2). This file allows us to distribute the code on [npm](https://www.npmjs.com/), so people can download it from their command line by typing `npm install dlx-js`.

* **dlx-api.js** - This is the main code for the project. We want everything to be contained in this single file, so that users can just download it and link to it in their pages - really easy.

Go ahead and close this issue once you're done reading it.

**Comment by jmangel** [comment]
OK, so dlx-api.js is the SDK file?

**Comment by dwhieb** [comment]
Exactly
