### ISSUE TITLE
decide the methods to include in dlx-api.js

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/dlx-js#6]
After looking at the [API repo](https://github.com/digitallinguistics/dlx-api), and the [API documentation](http://dlx-dev.azurewebsites.net/swagger.html), create a plan for what dlx-api.js should contain. You can see I already edited dlx-api.js to include a single object, `dlxApi`. This object will contain all the functions the user can call to do things with the API. We should add methods to dlxApi for each operation that can be performed on the database. Here are a few possible examples:

* dlxApi.getText() - sends a GET request to https://dlx.azurewebsites.net/v1/texts
* dlxApi.addTexts() - sends a PUT request to https://dlx.azurewebsites.net/v1/texts
* dlxApi.addPermission() - sends a POST request to https://dlx.azurewebsites.net/v1/user
etc. etc.

We want to make these methods as semantically transparent as possible.

So look at the API documentation, and add a section to the dlx-js readme outlining what methods you think we should have (in the dev branch). When you're done, make a pull request and tag me in it and we can discuss.

If you have any questions as you go, just add an issue and tag it as 'question'.

**Comment by dwhieb** [comment]
Now that I think about this more, go ahead and add your suggested methods directly to the dlxApi object, rather than the readme. The whole point of using JSDoc is so that we *don't* have to write the readme separately - it'll be automatically generated from your comments in the code.

I'll add my couple sample methods to the dlxApi object so you can see what I mean.

**Comment by dwhieb** [comment]
Note that I'm using a new syntax for method definitions available in ES6: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions.

It used to be you needed to write `getTexts: function () { /* function code here */ }` inside of an object. Now you can just write `getTexts () { /* function code here */ }`.

**Comment by jmangel** [comment]
@dwhieb is a 'collection' the general term for for bundles, texts, and lexicons? Take a look at the methods I've added to the dev branch and see if that about covers it. I'm taking them from the "URI Syntax" in the DLX-API readme. Let me know if I should add methods for languages, locations, media, persons, projects, users.

**Comment by dwhieb** [comment]
Yeah, the database we're using (Azure DocumentDB) calls things 'collections' rather than 'tables'. In the API readme, I think I included a list of all our collections - texts, persons, lexicons, etc. A 'bundle' is a linguistics term, for a group of related documentary resources. Say you record a text, and have separate files for the audio and the transcription and field notes on it, etc. All of those go in a single bundle for that session.

**Comment by jmangel** [comment]
@dwhieb does pull request #7 close this issue?

**Comment by dwhieb** [comment]
Let's finish the permissions stuff first
